import { build } from 'esbuild';
import { readFileSync, writeFileSync, readdirSync, mkdirSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { matter } from './lib/frontmatter.mjs';

export async function buildRuntime({ check = false } = {}) {
  const root = fileURLToPath(new URL('../', import.meta.url));
  const skills = readdirSync(root + 'skills').filter(name => /^oc-/.test(name)).sort()
    .map(name => matter(readFileSync(root + `skills/${name}/SKILL.md`, 'utf8')).data);
  const catalog = JSON.stringify({ skills: skills.map(skill => skill.name),
    phases: [...new Set(skills.flatMap(skill => skill.phases))].sort(),
    commands: [...new Set(skills.flatMap(skill => skill.commands.map(command => command.split(' ')[0])))].sort(),
  }, null, 2) + '\n';
  const catalogPath = new URL('./runtime/catalog.json', import.meta.url);
  let oldCatalog;
  try { oldCatalog = readFileSync(catalogPath, 'utf8'); } catch {}
  if (oldCatalog !== catalog) {
    if (check) throw new Error('Runtime catalog drift. Run npm run sync-bundles.');
    writeFileSync(catalogPath, catalog);
  }
  const result = await build({ absWorkingDir: root,
    entryPoints: ['scripts/runtime/prompt-engine-entry.mjs'], bundle: true,
    platform: 'node', target: 'node22', format: 'esm', write: false,
    legalComments: 'inline', minify: true,
    banner: { js: '// Generated by scripts/build-runtime.mjs. Source: prompt-engine-entry.mjs and its imports.' },
  });
  for (const dependency of ['zod', 'js-yaml']) {
    const license = readFileSync(root + `node_modules/${dependency}/LICENSE`, 'utf8');
    const target = root + `scripts/runtime/licenses/${dependency}.txt`;
    let prior; try { prior = readFileSync(target, 'utf8'); } catch {}
    if (prior !== license) {
      if (check) throw new Error(`Runtime license drift: ${dependency}`);
      mkdirSync(root + 'scripts/runtime/licenses', { recursive: true });
      writeFileSync(target, license);
    }
  }
  const output = new URL('./runtime/prompt-engine.mjs', import.meta.url);
  const expected = result.outputFiles[0].text;
  let actual;
  try { actual = readFileSync(output, 'utf8'); } catch {}
  if (actual === expected) return;
  if (check) throw new Error('Prompt engine bundle drift. Run npm run sync-bundles.');
  writeFileSync(output, expected);
}
if (process.argv[1] === fileURLToPath(import.meta.url)) await buildRuntime({ check: process.argv.includes('--check') });
