#!/usr/bin/env node
// Read-only package inspection. Presence is never evidence of host execution.
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const modes = ['source', 'claude-plugin', 'skills', 'local-mcp', 'hosted-mcp', 'runtime'];
const exists = (root, file) => fs.existsSync(path.join(root, file));
function names(root, suffix) {
  if (!fs.existsSync(root)) return [];
  return fs.readdirSync(root, { withFileTypes: true })
    .filter(entry => entry.isFile() && entry.name.endsWith(suffix))
    .map(entry => entry.name).sort();
}
function skills(root) {
  if (!fs.existsSync(root)) return [];
  return fs.readdirSync(root, { withFileTypes: true })
    .filter(entry => entry.isDirectory() && exists(root, `${entry.name}/SKILL.md`))
    .map(entry => entry.name).sort();
}

export function inspectPackage(root, mode) {
  if (!modes.includes(mode)) throw new Error(`mode must be one of: ${modes.join(', ')}`);
  root = path.resolve(root);
  const errors = [];
  const plugin = mode === 'source' ? path.join(root, 'plugins/opchain') : root;
  const skillRoot = mode === 'skills' ? root : path.join(root, 'skills');
  const result = {
    schema: 'opchain.capabilities', version: 1, mode,
    assurance: 'artifact inspection only; host execution and enrollment unverified',
    skills: mode === 'hosted-mcp' ? null : skills(skillRoot),
    commands: [], hooks: [], runtime_files: {}, errors,
  };
  if (mode === 'source' || mode === 'claude-plugin') {
    result.commands = names(path.join(plugin, 'commands'), '.md');
    try {
      const config = JSON.parse(fs.readFileSync(path.join(plugin, 'hooks/hooks.json'), 'utf8'));
      for (const [event, entries] of Object.entries(config.hooks ?? {})) {
        for (const entry of entries) for (const hook of entry.hooks ?? []) {
          const match = /^node "\$\{CLAUDE_PLUGIN_ROOT\}\/([^"\r\n]+)"$/.exec(hook.command ?? '');
          const safe = match && !match[1].split('/').includes('..') && !path.isAbsolute(match[1]);
          const present = Boolean(hook.type === 'command' && safe && exists(plugin, match[1]));
          result.hooks.push({ event, matcher: entry.matcher ?? null, script: safe ? match[1] : null, present });
          if (!present) errors.push(`${event}: unsupported hook type/command form or missing hook script`);
        }
      }
      if (!result.hooks.length) errors.push('hook manifest declares no hooks');
    } catch (error) { errors.push(`hook manifest: ${error.message}`); }
  }
  if (mode === 'source' || mode === 'local-mcp' || mode === 'runtime') {
    result.runtime_files.local_mcp = exists(root, 'mcp/local-server.mjs');
    if (!result.runtime_files.local_mcp) errors.push('local MCP entry point missing');
  }
  if (mode === 'source' || mode === 'runtime') {
    result.runtime_files.candidate_verifier = exists(root, 'scripts/verify-candidate.mjs') && exists(root, 'scripts/lib/verification-receipt.cjs');
    result.runtime_files.prompt_eval = exists(root, 'scripts/prompt-eval.mjs');
    result.runtime_files.cost = exists(root, 'scripts/cost.mjs');
    if (mode === 'runtime') for (const [name, present] of Object.entries(result.runtime_files)) {
      if (!present) errors.push(`runtime entry files missing: ${name}`);
    }
  }
  if (mode !== 'hosted-mcp' && !result.skills.length) errors.push('no skill instructions found');
  result.limits = {
    runtime: 'Private local runtime artifact; no host hook registration. Entry files must be present, dependencies/loadability require the separate artifact smoke test. Commit verification requires explicit target enrollment.',
    source: 'Local commit enforcement requires explicit repository enrollment; protected CI must verify its own candidate.',
    'claude-plugin': 'SessionStart/Stop require Node and a supporting Claude host. Run /oc-enroll successfully per repository for Git commit verification; installation alone does not activate it.',
    skills: 'Instructions and bundled references only. No host hook registration or repository-level runtime is supplied by this delivery mode.',
    'local-mcp': 'Project-local state and skill resources; filesystem locking and runtime dependencies must pass startup checks. No commit authority is conveyed by checkpoints.',
    'hosted-mcp': 'Remote resources and session state are advisory. No local filesystem or commit enforcement; server availability is not inspected here.',
  }[mode];
  return result;
}

export function capabilityMarkdown(root) {
  const source = inspectPackage(root, 'source');
  const plugin = inspectPackage(path.join(root, 'plugins/opchain'), 'claude-plugin');
  const runtime = inspectPackage(root, 'runtime');
  return `# Package capabilities\n\nGenerated by \`npm run capabilities:generate\`. Counts describe inspected source/plugin directories, not observed native-host execution. ZIP counts below are packaging expectations derived from source; built ZIP contents require separate artifact validation.\n\n| Delivery | Instructions | Command wrappers | Registered hooks | Assurance and limits |\n|---|---:|---:|---:|---|\n| Source checkout | ${source.skills.length} | ${source.commands.length} in plugin | ${source.hooks.length} in plugin | ${source.limits} |\n| Claude plugin | ${plugin.skills.length} | ${plugin.commands.length} | ${plugin.hooks.length} | ${plugin.limits} |\n| Skills ZIP / copied Codex skills | ${source.skills.length} expected in combined ZIP; 1 expected per-skill ZIP | 0 | 0 | ${inspectPackage(path.join(root, 'skills'), 'skills').limits} |\n| Portable local runtime | ${source.skills.length} | npm CLI entry points | 0 | ${runtime.limits} |\n| Local MCP | Resource API | Protocol tools, not host slash wrappers | 0 | ${inspectPackage(root, 'local-mcp').limits} |\n| Hosted MCP | Resource API | Protocol tools, not host slash wrappers | 0 | ${inspectPackage(root, 'hosted-mcp').limits} |\n\nRun \`node scripts/capabilities.mjs --mode MODE --root ARTIFACT_ROOT\` before configuring an install. Modes: ${modes.join(', ')}. The read-only diagnostic emits versioned JSON and exits 1 for missing/malformed required package files, 2 for invalid arguments. For skills mode, point at the directory containing skill folders. The diagnostic itself ships in the source checkout; it does not require installation or modify the inspected artifact. runtime_files reports entry-file presence only, not loadability. Host execution, Git enrollment, dependency availability and external-provider access require separate runtime checks.\n`;
}

function main(args) {
  try {
    if (args[0] === '--generate' && args.length === 1) {
      const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
      fs.writeFileSync(path.join(root, 'docs/capabilities.md'), capabilityMarkdown(root));
      return;
    }
    const flags = {};
    for (let i = 0; i < args.length; i += 2) {
      if (!['--root', '--mode'].includes(args[i]) || !args[i + 1] || args[i + 1].startsWith('--') || flags[args[i]]) throw new Error('expected --mode MODE [--root PATH]');
      flags[args[i]] = args[i + 1];
    }
    const result = inspectPackage(flags['--root'] ?? process.cwd(), flags['--mode']);
    console.log(JSON.stringify(result, null, 2));
    process.exitCode = result.errors.length ? 1 : 0;
  } catch (error) { console.error(error.message); process.exitCode = 2; }
}
if (process.argv[1] && fs.realpathSync(process.argv[1]) === fs.realpathSync(fileURLToPath(import.meta.url))) main(process.argv.slice(2));
